name: simple_loading_button
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  animated_size_and_fade: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
